# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Get certificates"
  lane :certificates do
    sync_code_signing(
      type: "development",
      app_identifier: ['com.keevault.keevault.dev'],
      force_for_new_devices: true,
      readonly: true
    )

    sync_code_signing(
      type: "appstore",
      app_identifier: ['com.keevault.keevault', 'com.keevault.keevault.beta'],
      readonly: true
    )

    sync_code_signing(
      type: "adhoc",
      app_identifier: ['com.keevault.keevault', 'com.keevault.keevault.beta', 'com.keevault.keevault.dev'],
      readonly: true
    )
  end

  desc "Generate new certificates"
  lane :generate_new_certificates do
    sync_code_signing(
      type: "development",
      app_identifier: ['com.keevault.keevault.dev'],
      force_for_new_devices: true,
      readonly: false
    )
    
    sync_code_signing(
      type: "appstore",
      app_identifier: ['com.keevault.keevault', 'com.keevault.keevault.beta'],
      readonly: false
    )

    sync_code_signing(
      type: "adhoc",
      app_identifier: ['com.keevault.keevault', 'com.keevault.keevault.beta', 'com.keevault.keevault.dev'],
      readonly: false
    )
  end

  ### Warning!! Only thing that determines whether this points at beta or prod servers is 
  # the command most recently executed!
  desc "Push a new beta build to test service"
  lane :beta_stage do
    match(
      type: "adhoc",
      app_identifier: 'com.keevault.keevault.beta'
    )
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    testfairy(api_key: "TODO: env var",
      testers_groups: ['ios'],
      notify: 'on'
    )
    #upload_to_testflight
  end

  desc "Push a new prod build to testflight"
  lane :prod_stage_testflight do
    match(
      type: "appstore",
      app_identifier: 'com.keevault.keevault'
    )
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_testflight
  end
end
