# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "release to all beta testers"
  lane :beta do
  upload_to_play_store(
    aab: "../build/app/outputs/bundle/release/app-release.aab",
    track: "beta",
    skip_upload_apk: true,
    skip_upload_changelogs: false,
    skip_upload_images: false,
    skip_upload_screenshots: false,
    skip_upload_metadata: false,
    version_name: flutter_version()["version_code"] + " (" + flutter_version()["version_name"] + ")"
  )
  end

  desc "Push a new beta build to test service"
  lane :beta_stage do
    testfairy(api_key: ENV["TESTFAIRY_API_KEY"],
      testers_groups: ['android'],
      notify: 'on',
      apk: '../build/app/outputs/flutter-apk/app-release.apk'
    )
  end

  desc "upload new android screenshots for review but no other items"
  lane :screenshots_only do
  upload_to_play_store(
    #aab: "../build/app/outputs/bundle/release/app-release.aab",
    track: "beta",
    skip_upload_apk: true,
    skip_upload_aab: true,
    skip_upload_changelogs: true,
    skip_upload_images: true,
    skip_upload_screenshots: false,
    skip_upload_metadata: true,
    #version_name: flutter_version()["version_code"] + " (" + flutter_version()["version_name"] + ")"
  )
  end
end
