# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "release to internal testers only"
  lane :internal do
  upload_to_play_store(
    aab: "../build/app/outputs/bundle/release/app-release.aab",
    track: "internal",
    skip_upload_apk: true,
    skip_upload_changelogs: true,
    skip_upload_images: true,
    skip_upload_screenshots: true,
    skip_upload_metadata: true,
    version_name: flutter_version()["version_code"] + " (" + flutter_version()["version_name"] + ")"
  )
  end

  desc "Promote to limited set of testers"
  lane :alpha do
  upload_to_play_store(
    track: "internal",
    track_promote_to: "alpha",
    skip_upload_aab: true,
    skip_upload_apk: true,
    skip_upload_changelogs: false,
    skip_upload_images: false,
    skip_upload_screenshots: false,
    skip_upload_metadata: false,
    version_code: flutter_version()["version_code"] 
  )
  end

  desc "Promote to all beta testers"
  lane :beta do
  upload_to_play_store(
    track: "alpha",
    track_promote_to: "beta",
    skip_upload_aab: true,
    skip_upload_apk: true,
    skip_upload_changelogs: true,
    skip_upload_images: true,
    skip_upload_screenshots: true,
    skip_upload_metadata: true,
    version_code: flutter_version()["version_code"] 
  )
  end

end
